### ISSUE TITLE
 No module named 'jaxrl_m.vision.bigvision_resnetv2'

### ISSUE THREAD

**Issue by Alpslee** [rail-berkeley/soar#10]
try to run model training on ubuntu with gpu 4090 :
bash experiments/scripts/launch.sh
I got the error:
Traceback (most recent call last):
  File "/root/soar/model_training/experiments/train.py", line 20, in <module>
    from jaxrl_m.utils.train_utils import pretrained_loaders
  File "/root/soar/model_training/jaxrl_m/utils/train_utils.py", line 11, in <module>
    from jaxrl_m.vision.bigvision_resnetv2 import load
ModuleNotFoundError: No module named 'jaxrl_m.vision.bigvision_resnetv2'

I followed the instructions and installed all requirements,any suggestions ?thanks

**Comment by zhouzypaul** [comment]
Hi Alpslee, 

I just pushed a fix on main that should solve this for you. You can check it out [here](https://github.com/rail-berkeley/soar/commit/3f4f447e94f25d96bc94785f2167ebc1275134c3). Thanks for letting us know! 

Let me know if you run into any more issues.

**Comment by zhouzypaul** [comment]
Closing due to inactivity. Feel free to open again if you run into more issues.
